services:
  postgres:
    image: postgres:16
    container_name: thesis_db
    environment:
      POSTGRES_DB: thesis
      POSTGRES_USER: thesis_user
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U thesis_user -d thesis"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/thesis
      SPRING_DATASOURCE_USERNAME: thesis_user
      SPRING_DATASOURCE_PASSWORD: 12345
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: